server:
  port: 9090
  # https://advanced-real-estate-be.onrender.com
  host: ${SERVER_HOST:advanced-real-estate-be.onrender.com}  

app:
  protocol: ${APP_PROTOCOL:https}

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  signerKey: ${JWT_SECRET}
  valid-duration: 3600
  refreshable-duration: 36000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    enable: true
  group-configs:
    - group: advancedRealEstate_BE
      paths-to-match: /api/**

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
    debug: true

python:
  api:
    base-url: ${PYTHON_API_URL:http://localhost:5000}
