# ---------- STAGE 1: Build ứng dụng ----------
FROM maven:3.9.4-eclipse-temurin-21 AS build

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests


# ---------- STAGE 2: Chạy ứng dụng ----------
FROM openjdk:21-slim

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
